language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - pecl install oauth
  - echo "extension=oauth.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

script:
  - cd tests
  - php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml

after_script:
  - php ../vendor/bin/coveralls -v